# Generated by Django 4.2.14 on 2024-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('surfbreak', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
